### ISSUE TITLE
Update issue?

### ISSUE THREAD

**Issue by dejavu030507** [gnustavo/JIRA-REST#18]
Hello,

I couldn't update my Jira Issue's status by using JIRA-REST..

I have to change transition via Perl. Could you please help me?

Thank you.

**Comment by gnustavo** [comment]
Hi. I'm sorry for the delay. There are a [few examples now in the distribution](https://github.com/gnustavo/JIRA-REST/tree/next/examples).

Please, take a look to see if they help you out. If not, show me your script and the error you're getting so that I can investigate further.
