### ISSUE TITLE
Catching 'errorMessage' Jira errors

### ISSUE THREAD

**Issue by mrmaloof** [gnustavo/JIRA-REST#20]
Here is another way Jira gives us its error message with the key 'errorMessage' which JIRA-REST does not capture.

`$VAR1 = {
          'i18nErrorMessage' => {
                                  'i18nKey' => 'sd.validation.request.creation.failure.required.field',
                                  'parameters' => [
                                                    'This customer is inactive. You\'ll need to go to user management and activate their account before you can invite them to the Service Desk.'
                                                  ]
                                },
          'errorMessage' => 'Your request could not be created. Please check the fields have been correctly filled in. This customer is inactive. You\'ll need to go to user management and activate their account before you can invite them to the Service Desk.'
        }`

**Comment by gnustavo** [comment]
Thanks, William. I just merged you pull request about this.
