### ISSUE TITLE
Documentation update request for dealing with proxies

### ISSUE THREAD

**Issue by padraiglennon** [gnustavo/JIRA-REST#3]
Hi

Would it be possible to update the documentation to include an example of how to properly work with proxies? I have been trying a number of approaches all of which have been failing. 

What is the correct syntax for passing proxy information to the new() function?

**Comment by gnustavo** [comment]
Good idea!

However, the code to let JIRA::REST use proxies was contributed by Andrew OBrien in 4d828831 but I never used proxies myself.

Supposing you invoked new like this:

``` perl
my $jira = JIRA::REST->new(JIRAURL, USER, PASS, {proxy => PROXYURL});
```

What is does is to get an LWP::UserAgent object and invoke its proxy method like this:

``` perl
$ua->proxy(['http','https'], PROXYURL);
```

You can read about that method [here](https://metacpan.org/pod/LWP::UserAgent#Proxy-attributes).

Does this help?

If not, show me the code you're using the error you're getting, please.

**Comment by padraiglennon** [comment]
That works. Thank you for that
